### ISSUE TITLE
Api endpoints to re/set features

### ISSUE THREAD

**Issue by masduo** [SeatwaveOpenSource/jsonmraz#1]
Good stuff for the read side of things, however what do you think about the write? are there going to be new authorized endpoints to allow setting the features, or a different service. I remember in initial conversations we were thinking of having a different service. But not sure how that evolved with this initial implementation.

**Comment by ryancosans** [comment]
good question there isn't any reason this can't also handle the writing

**Comment by ryancosans** [comment]
see the [add editable endpoint](https://github.com/SeatwaveOpenSource/jsonmraz/tree/add_editable_endpoint) branch

**Comment by ryancosans** [comment]
#4 this is covered here
